global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NestJS API Service
  - job_name: 'nestjs-api'
    static_configs:
      - targets: ['nestjs-api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Python Service
  - job_name: 'python-service'
    static_configs:
      - targets: ['python-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Go Service
  - job_name: 'golang-service'
    static_configs:
      - targets: ['golang-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s 